version: '3.7'
services:
   sonarqube:
     image: sonarqube:9.9.3-community
     container_name: sonarqube
     #restart: always
     volumes:
       - ./data:/opt/sonarqube/data
       - ./logs:/opt/sonarqube/logs
       - ./extensions:/opt/sonarqube/extensions
       #- ./conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
     ports:
       - 9002:9000
       - 9003:9001
     environment:
       SONAR_JDBC_URL: jdbc:postgresql://db/${DATABASE_NAME}
       SONAR_JDBC_USERNAME: ${DATABASE_USER}
       SONAR_JDBC_PASSWORD: ${DATABASE_PASSWORD}

   db:
     image: postgres:13
     container_name: sonarqube_db
     environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres 
     env_file:
       - ./.env
     volumes:
       - ./pg_data:/var/lib/postgresql/data:consistent
       - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
