#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
   CREATE USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASSWORD}';
   CREATE DATABASE ${DATABASE_NAME} OWNER ${DATABASE_USER};
   GRANT ALL PRIVILEGES ON DATABASE ${DATABASE_NAME} to ${DATABASE_USER};
EOSQL
